services:
  tesla:
    image: ${REGISTRY:-spacetimehub}/tesla:${VERSION:-latest}
    container_name: tesla 
    restart: unless-stopped
    labels:
        - "traefik.enable=true"                                                                                                      
        - "traefik.http.routers.tesla.rule=Host(`tesla.${DOMAIN:-localhost}`)"
        - "traefik.http.routers.tesla.entrypoints=websecure"                                                                        
        - "traefik.http.routers.tesla.tls.certresolver=letsencrypt"
        - "traefik.http.services.tesla.loadbalancer.server.port=80"   
    networks:
      - spacetime_default

networks:
  spacetime_default:
    external: true
