services:
  tuya:
    image: ${REGISTRY:-spacetimehub}/tuya:${VERSION:-latest}
    container_name: tuya
    restart: unless-stopped
    ports:
      - "3095:80"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
