services:
  tuya:
    image: ${REPOSITORY:-spacetimehub}/tuya:${IMAGE_TAG:-latest}
    container_name: tuya 
    restart: unless-stopped
    labels:
        - "traefik.enable=true"                                                                                                      
        - "traefik.http.routers.tuya.rule=Host(`tuya.${DOMAIN:-localhost}`)"
        - "traefik.http.routers.tuya.entrypoints=websecure"                                                                        
        - "traefik.http.routers.tuya.tls.certresolver=letsencrypt"
        - "traefik.http.services.tuya.loadbalancer.server.port=3095"   
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
