services:
  tuya:
    image: ${REGISTRY:-spacetimehub}/tuya:${VERSION:-latest}
    container_name: tuya
    restart: unless-stopped
    ports:
      - "3095:80"
    networks:
      - spacetime_default

networks:
  spacetime_default:
    external: true
