services:
  count:
    image: ${REGISTRY:-spacetimehub}/count:${VERSION:-latest}
    container_name: count
    restart: unless-stopped
    ports:
      - "8097:80"
    networks:
      - spacetime_default

networks:
  spacetime_default:
    external: true