services:
  crawler:
    image: ${REGISTRY:-spacetimehub}/crawler:${VERSION:-latest}
    container_name: crawler
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - spacetime_default

networks:
  spacetime_default:
    external: true