services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: idata
    volumes:
      - ${DATA:-.}/mongo:/data/db
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - ${DATA:-.}/qdrant:/qdrant/storage
  server:
    image: ${REPOSITORY:-spacetimehub}/server:${IMAGE_TAG:-latest}
    container_name: server
    restart: unless-stopped
    ports:
      - "8010:80"
    environment:
      MONGODB_URI: mongodb://mongo/idata
      AGENT_URL: http://agent
      MODE: production
      JWT: "false"
      LOGLEVEL: info
      TZ: Europe/Amsterdam
      LATITUDE: 51.41191 
      LONGITUDE: 5.44969 
    volumes:
      -  ${DATA:-.}/server:/usr/src/app/data
    depends_on:
      - mongo
  portal:
    image: ${REPOSITORY:-spacetimehub}/portal:${IMAGE_TAG:-latest}
    container_name: portal
    restart: unless-stopped
    ports:
      - "3000:80"
  forms:
    image: ${REPOSITORY:-spacetimehub}/forms:${IMAGE_TAG:-latest}
    container_name: forms 
    restart: unless-stopped
    ports:
      - "3002:80"
  modeler:
    image: ${REPOSITORY:-spacetimehub}/modeler:${IMAGE_TAG:-latest}
    container_name: modeler 
    restart: unless-stopped
    ports:
      - "3005:80"
  draw:
    image: ${REPOSITORY:-spacetimehub}/draw:${IMAGE_TAG:-latest}
    container_name: draw 
    restart: unless-stopped
    ports:
      - "3006:80"
  agent:
    image: ${REPOSITORY:-spacetimehub}/agent:${IMAGE_TAG:-latest}
    container_name: agent
    restart: unless-stopped
    environment:
      QDRANT_URL: http://qdrant:6333
      SERVER_URL: http://server
      COHERE_API_KEY: ${COHERE_API_KEY:-IcuIOyBY6kDdeaA70wTXal7kyAN5TbQ5ywuRtjR9} 
      LLM: cohere
